CREATE OR REPLACE DATABASE COHORT;
USE COHORT;


CREATE OR REPLACE TABLE RETAIL (
    InvoiceNo varchar(100),
    StockCode varchar(20),
    Description varchar(100),
    Quantity decimal(8,2), 
    InvoiceDate varchar(25),
    UnitPrice decimal(8,2), 
    CustomerID varchar(100),  
    Country varchar(25)
);

SELECT * FROM RETAIL;

SELECT DISTINCT EXTRACT('YEAR', TO_DATE(INVOICEDATE, 'DD/MM/YY HH24:MI')) AS YEARS 
FROM RETAIL;



-- ----------------------------------------------- COHORT ANALYSIS ------------------------------------------------ 

-- REVENUE LEVEL COHORT

WITH CTE1 AS (
SELECT CUSTOMERID, TO_DATE(INVOICEDATE, 'DD/MM/YY HH24:MI') AS INVOICEDATE,
       ROUND((QUANTITY * UNITPRICE), 0) AS REVENUE
FROM RETAIL
WHERE CUSTOMERID IS NOT NULL AND QUANTITY > 0 AND UNITPRICE > 0
),

CTE2 AS (
SELECT CUSTOMERID, REVENUE,
       DATE_TRUNC('MONTH', INVOICEDATE) AS PURCHASE_MONTH,
       DATE_TRUNC('MONTH', MIN(INVOICEDATE) OVER(PARTITION BY CUSTOMERID ORDER BY INVOICEDATE)) AS FIRST_PURCHASE_MONTH
FROM CTE1
), 

CTE3 AS (
SELECT REVENUE, FIRST_PURCHASE_MONTH, 
       CONCAT('MONTH_', DATEDIFF('MONTH', FIRST_PURCHASE_MONTH, PURCHASE_MONTH)) AS COHORT_MONTH
FROM CTE2
)

SELECT *,
FROM CTE3 
PIVOT(SUM(REVENUE) FOR COHORT_MONTH IN(
'MONTH_0', 'MONTH_1', 'MONTH_2', 'MONTH_3', 'MONTH_4', 'MONTH_5', 'MONTH_6', 'MONTH_7', 'MONTH_8', 'MONTH_9', 'MONTH_10', 'MONTH_11', 'MONTH_12'
))
ORDER BY FIRST_PURCHASE_MONTH;


-- CUSTOMER LEVEL COHORT

WITH CTE1 AS (
SELECT CUSTOMERID, TO_DATE(INVOICEDATE, 'DD/MM/YY HH24:MI') AS INVOICEDATE
FROM RETAIL
WHERE CUSTOMERID IS NOT NULL
),

CTE2 AS (
SELECT CUSTOMERID,
       INVOICEDATE,
       DATE_TRUNC('MONTH', INVOICEDATE) AS PURCHASE_MONTH,
       DATE_TRUNC('MONTH', MIN(INVOICEDATE) OVER(PARTITION BY CUSTOMERID ORDER BY INVOICEDATE)) AS FIRST_PURCHASE_MONTH
FROM CTE1
),

CTE3 AS (
SELECT CUSTOMERID, FIRST_PURCHASE_MONTH,
       CONCAT('MONTH_', DATEDIFF('MONTH', FIRST_PURCHASE_MONTH, PURCHASE_MONTH)) AS COHORT_MONTH
FROM CTE2
GROUP BY CUSTOMERID, FIRST_PURCHASE_MONTH, PURCHASE_MONTH)

SELECT *,
FROM CTE3
PIVOT(COUNT(CUSTOMERID) FOR COHORT_MONTH IN (
'MONTH_0', 'MONTH_1', 'MONTH_2', 'MONTH_3', 'MONTH_4', 'MONTH_5', 'MONTH_6', 'MONTH_7', 'MONTH_8', 'MONTH_9', 'MONTH_10', 'MONTH_11', 'MONTH_12'
))
ORDER BY FIRST_PURCHASE_MONTH;


-- ORDER LEVEL COHORT


WITH CTE1 AS (
SELECT INVOICENO, CUSTOMERID, TO_DATE(INVOICEDATE, 'DD/MM/YY HH24:MI') AS INVOICEDATE
FROM RETAIL
WHERE CUSTOMERID IS NOT NULL
),

CTE2 AS (
SELECT INVOICENO, CUSTOMERID,
       INVOICEDATE,
       DATE_TRUNC('MONTH', INVOICEDATE) AS PURCHASE_MONTH,
       DATE_TRUNC('MONTH', MIN(INVOICEDATE) OVER(PARTITION BY CUSTOMERID ORDER BY INVOICEDATE)) AS FIRST_PURCHASE_MONTH
FROM CTE1
),

CTE3 AS (
SELECT INVOICENO, FIRST_PURCHASE_MONTH,
       CONCAT('MONTH_', DATEDIFF('MONTH', FIRST_PURCHASE_MONTH, PURCHASE_MONTH)) AS COHORT_MONTH
FROM CTE2
GROUP BY INVOICENO, FIRST_PURCHASE_MONTH, PURCHASE_MONTH)

SELECT *,
FROM CTE3
PIVOT(COUNT(INVOICENO) FOR COHORT_MONTH IN (
'MONTH_0', 'MONTH_1', 'MONTH_2', 'MONTH_3', 'MONTH_4', 'MONTH_5', 'MONTH_6', 'MONTH_7', 'MONTH_8', 'MONTH_9', 'MONTH_10', 'MONTH_11', 'MONTH_12'
))
ORDER BY FIRST_PURCHASE_MONTH;